# WARNING
# Do not try to delete lines or else the script will break DO NOT Report github issues for this its your fault your Warned!

[Sound Theme]
# Change the Sound Theme to themes that are on the themes folder
# E.g / Windows 11

# sound_theme
Default

[Battery Levels]
# Change the Battery threshold to a
n number
# E.g low_battery_level = 15 or 30

# low_battery_level
15

# full_battery_level
95

# dead_battery_level
10